[24.11.24 / TASK-42] Feature - Model migration
Check-Data-Out/velog-dashboard-v2-back-office pull request #3
Opened 2024-11-28 18:19 UTC by BDlhj

### 작업 내용
- 데이터베이스 설정 관련하여 README.md 업데이트
- User, Post, PostStatistics, PostDailyStatistics 모델 생성 및 마이그레이션
- 최소한의 admin 기능 사용 가능

2024-11-29 07:39 UTC, Nuung commented on posts/admin.py
> +admin.site.register(PostDailyStatistics)
`register` 말고 class based 로 데코레이터 이용한 model 등록을 해주세요!
단순해도 괜찮으니까요~ ex는 아래와 같습니다~

```
@admin.register(Notice) 
class NoticeAdmin(admin.ModelAdmin):
    list_display = ['title', 'likeCount', 'viewCount']
    list_display_links = ['title', 'likeCount', 'viewCount']
```

2024-11-29 07:40 UTC, Nuung commented on pyproject.toml
> +psycopg = "^3.2.3"
웬만하면 `psycopg*-binary` 가 좋습니다. 이유는 한 줄 요약하면 의존성 입니다! (찾아보시는게 좋아요)

2024-11-29 07:41 UTC, Nuung commented on users/admin.py
이하 동문입니다.

2024-11-29 07:41 UTC, Nuung commented on users/utils.py
> +    return random.randint(1, 10)
사실 랜덤 그룹은 1~1000개 사이로 하려고 했고
그럼 왜 암호화 토큰이 10개인데? 라고 한다면, 그룹 값 `%100` 연산 을 하려고 했습니다

2024-11-29 07:44 UTC, Nuung commented on posts/models.py
1. 저는 기본적으로 model 에서 대부분의 field 를 명시해줍니다. 특히 `blank=False, null=False,` 과 같이 기본 값이 있음에도 말이죠
2. 그리고 그에 따라 help_text 는 가능하면 쓰려고 합니다. 근데 사실 지금 여기서는 필요 없을 것 같은 생각엔 동의합니다!
3. `created_at` 과 `updated_at` 이 모두 있다면 이는 따로 모델을 빼는게 좋습니다. 예시는 아래와 같습니다.

```python
class BaseModel(models.Model):
    """생성일, 수정일 필드 베이스 모델"""

    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="생성일",
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name="수정일",
    )

    class Meta:
        abstract = True
```

2024-11-29 07:48 UTC, Nuung requested changes
### 좋았던 점
- 모델과 어드민, 기본적인 사항을 모두 셋업하려고 고민하신 흔적이 느껴져서 좋았습니다.
- timesacleDB 공부하셨군요! 멋있습니다!

### 개선 요청 사항
1. 전체 코멘트 한 번 확인해 주세요! 특히 "어드민 사용자" 를 어떻게 할 것인가? 에 대한 결정이 필요해 보입니다! (무조건 필요하다! 라기 보다는 있으면? 따로 오버라이딩해서 만들지 않으면? 에 대한 고민이 필요할 것 같습니다)
2. 대시보드 사용자 말고, admin 사용자에 대한 모델은 어떻게 할 예정인가요?
3. 현재 default dbms 세팅이 timesacleDB 인 것 같은데, 이를 위한 `docker-compose.yaml` 은 기본적으로 있으면 매우 좋을 것 같습니다.

2024-11-29 08:23 UTC, HA0N1 approved these changes
### 좋았던 점
1. verbose_name을 한글로 설정하셔 가독성을 높이는 데 큰 도움이 될 것 같습니다!
2. `__str__`에서 UUID를 반환해 식별에 강점을 가져올 수 있을 거 같습니다! (사용자 보기 편하라고만 짜봤지 관리자 페이지 관점에서 생각해볼 수 있어 좋았습니다!)
### 그 외
unique_together는 최신 Django 버전에서 더 이상 지원하지 않을 예정이라고 합니다! constraints를 사용하라고 권장되어 있는데 참고 하시면 좋을 거 같아 링크 남깁니다!
https://docs.djangoproject.com/en/5.1/ref/models/options/#unique-together

2024-11-29 08:38 UTC, Nuung commented on posts/models.py
> +        unique_together = ("post", "date")
아 추가로 이거 없이 가봅시다 일단! 이유는 timesacledb 가 TimescaleDateTimeField 로 잡은 인터벌대로 어짜피 횡적 파티셔닝을 합니다! 굳이 추가적인 유니크는 필요 없을 것 같습니다~

2024-11-29 09:54 UTC, six-standard approved these changes
### 좋았던 점
- README에 명령어 설명이 나와있는 점이 좋았습니다. (사용 방법을 쉽게 배울 수 있겠네요.)
- DB 값을 env로 바꾼 점이 좋았습니다. (값 변경이 훨씬 쉬울 것 같습니다!)

2024-11-29 10:01 UTC, BDlhj commented on posts/admin.py
> +admin.site.register(PostDailyStatistics)
아하 넵!! admin 관련 PR을 나중에 따로 올릴까 했는데 전체 골조는 지금 잡는 게 좋을 것 같네요 감사합니다!!

2024-11-29 10:03 UTC, BDlhj commented on users/utils.py
> +    return random.randint(1, 10)
놓친 부분 확인해주셔서 감사합니다!

2024-11-29 16:35 UTC, BDlhj commented
> ### 좋았던 점
> * 모델과 어드민, 기본적인 사항을 모두 셋업하려고 고민하신 흔적이 느껴져서 좋았습니다.
> * timesacleDB 공부하셨군요! 멋있습니다!
> 
> ### 개선 요청 사항
> 1. 전체 코멘트 한 번 확인해 주세요! 특히 "어드민 사용자" 를 어떻게 할 것인가? 에 대한 결정이 필요해 보입니다! (무조건 필요하다! 라기 보다는 있으면? 따로 오버라이딩해서 만들지 않으면? 에 대한 고민이 필요할 것 같습니다)
> 2. 대시보드 사용자 말고, admin 사용자에 대한 모델은 어떻게 할 예정인가요?
> 3. 현재 default dbms 세팅이 timesacleDB 인 것 같은데, 이를 위한 `docker-compose.yaml` 은 기본적으로 있으면 매우 좋을 것 같습니다.

admin 사용자 모델은 django에서 기본으로 제공하는 auth app의 user 모델을 사용하려고 했습니다!

2024-11-30 04:37 UTC, Nuung approved these changes
고생많으셨습니다! 드가봅시다!!!

2024-11-30 04:48 UTC, merged