[24.12.07 / TASK-43] Feature - tracking model 추가, admin 구성, 기본 세팅 업데이트
Check-Data-Out/velog-dashboard-v2-back-office pull request #4
Opened 2024-12-07 10:04 UTC by Nuung

- user data tracking 구성을 위해 모델링 선제 진행
- 세부 내용 하기 노션 참조 필수

> ***readme 파일도 상세 업데이트 완료***

2024-12-09 10:06 UTC, HA0N1 approved these changes
tacking 에 대해 한 번 더 고찰 할 수 있어 좋았습니다! 커밋메시지도 유쾌하네요!!

### 좋았던 점
- 이벤트 타입에 따라 코드값이 명확한 점과 설명 매핑이 체계젹인 거 같습니다!

2024-12-09 10:06 UTC, HA0N1 commented on tracking/tests/test_tracking_model_spec.py
> +            UserEventType.NOTHING,
NOTHING은 어떤걸 의미하는건가요?! 명시되지 않은 행동들의 값인가요? 임의의 값이라는게 정확히 무얼의미하는지 궁금합니다!

2024-12-09 14:55 UTC, BDlhj submitted a review, later dismissed
늦은 리뷰 죄송합니다...!!

### 좋았던 점
1. test ci와 readme 파일을 자세하게 고도화해주셔서 좋았습니다.
2. admin에서 데코레이터를 사용하는 게 훨씬 직관적인 것 같습니다. 추가로 필드셋도 미리 만들어서 그룹화해주신 것도 좋았습니다!

2024-12-09 14:55 UTC, BDlhj commented on backoffice/settings/test.py
전혀 모르고 있었는데 이 부분도 챙겨주셔서 감사합니다!

2024-12-09 14:55 UTC, BDlhj commented on tracking/models.py
> +class UserEventType(models.TextChoices):
개인적으로 궁금한 점인데 django를 사용하면 TextChoices를 사용하고 단순히 python을 사용할 때는 Enum을 사용하는 것이 일반적인가요?

2024-12-09 16:58 UTC, six-standard requested changes
회고록을 쓰다 보니 제가 꼴지가 됬군요;;

### 좋았던 점
- README와 ENV sample 파일이 확실해져서 어떤 방식으로 동작할지 이해하기 편했습니다!
- 중간중간 들어간 값과 코드 중 확장성을 고려하여 넣은 부분들이 있던데, 깊은 고민의 흔적이 보였습니다.

2024-12-09 16:58 UTC, six-standard commented on tracking/migrations/0001_initial.py
> +                (
이벤트 트래킹을 위한 모델로 보이는데, 과연 수정 일시가 필요할까 싶습니다.

2024-12-09 16:58 UTC, six-standard commented on tracking/admin.py
> +    search_fields = ("user__email", "event_type")
이 부분 노리신건지 모르겠는데 언더바가 두 개입니다

2024-12-10 07:36 UTC, Nuung commented on tracking/admin.py
> +    search_fields = ("user__email", "event_type")
디테일한 포인트 너무 감사해요!
django admin 에서 역참조한 필드 (관계를 맺고 있는데, 역참조 형태 관계 인 경우) 접근할때는 언더바 2개를 사용합니다! :)

2024-12-10 07:37 UTC, Nuung commented on tracking/migrations/0001_initial.py
> +                (
맞아요 사실 귀찮아서 모델 상속받아서 그냥 박았는데, 완벽한게 좋죠,, 맞아요 흐흐 안일했어요 제가!! 수정할게요 👍 👍 👍

2024-12-10 07:38 UTC, Nuung commented on tracking/models.py
> +class UserEventType(models.TextChoices):
옙 맞습니다~ 프레임워크에 의존성이 높아질수록 `Enum` 을 쓰는 경우도 꽤나 없을거에요! 오히려 파이덴틱으로 더 많이 하니..!

2024-12-10 14:49 UTC, merged